random_turn=true # true or false
initial_high_level_policy="fixed" # "fixed" or "fixed_2" or "random"
first_id=0 # 0 or 1
dt=0.01 # 0.01 or 0.02
max_population_size=2
drone_model="IrisTest"
run_name_suffix=""
num_envs=512
init_by_latest_strategy=true
seed=2

CUDA_VISIBLE_DEVICES=0 python ../train_coselfplay_phase_two.py headless=true \
    total_frames=5_000_000_000 \
    task=Coselfplay_Phase_two \
    Opp_FirstPass_goto_policy_checkpoint_path="checkpoint/checkpoint_goto.pt" \
    Opp_FirstPass_policy_checkpoint_path="checkpoint/checkpoint_firstpass_3.pt" \
    Opp_FirstPass_hover_policy_checkpoint_path="checkpoint/checkpoint_firstpass_hover_3.pt" \
    Opp_FirstPass_serve_policy_checkpoint_path="checkpoint/checkpoint_serve.pt" \
    Opp_FirstPass_serve_hover_policy_checkpoint_path="checkpoint/checkpoint_serve_hover.pt" \
    Opp_FirstPass_receive_policy_checkpoint_path="checkpoint/checkpoint_firstpass_receive.pt" \
    Opp_FirstPass_receive_hover_policy_checkpoint_path="checkpoint/checkpoint_firstpass_receive_hover.pt" \
    Opp_SecPass_goto_policy_checkpoint_path="checkpoint/checkpoint_goto.pt" \
    Opp_SecPass_policy_checkpoint_path="checkpoint/checkpoint_secpass_2.pt" \
    Opp_SecPass_hover_policy_checkpoint_path="checkpoint/checkpoint_secpass_hover_2.pt" \
    Opp_Att_goto_policy_checkpoint_path="checkpoint/checkpoint_goto.pt" \
    Opp_Att_policy_checkpoint_path="checkpoint/checkpoint_att_2.pt" \
    Opp_Att_hover_policy_checkpoint_path="checkpoint/checkpoint_att_hover_2.pt" \
    FirstPass_goto_policy_checkpoint_path="checkpoint/checkpoint_goto.pt" \
    FirstPass_policy_checkpoint_path="checkpoint/checkpoint_firstpass_3.pt" \
    FirstPass_hover_policy_checkpoint_path="checkpoint/checkpoint_firstpass_hover_3.pt" \
    FirstPass_serve_policy_checkpoint_path="checkpoint/checkpoint_serve.pt" \
    FirstPass_serve_hover_policy_checkpoint_path="checkpoint/checkpoint_serve_hover.pt" \
    FirstPass_receive_policy_checkpoint_path="checkpoint/checkpoint_firstpass_receive.pt" \
    FirstPass_receive_hover_policy_checkpoint_path="checkpoint/checkpoint_firstpass_receive_hover.pt" \
    SecPass_goto_policy_checkpoint_path="checkpoint/checkpoint_goto.pt" \
    SecPass_policy_checkpoint_path="checkpoint/checkpoint_secpass_2.pt" \
    SecPass_hover_policy_checkpoint_path="checkpoint/checkpoint_secpass_hover_2.pt" \
    Att_goto_policy_checkpoint_path="checkpoint/checkpoint_goto.pt" \
    Att_policy_checkpoint_path="checkpoint/checkpoint_att_2.pt" \
    Att_hover_policy_checkpoint_path="checkpoint/checkpoint_att_hover_2.pt" \
    task.sim.dt=${dt} \
    task.sim.substeps=1 \
    task.env.num_envs=${num_envs} \
    task.use_trained_state=true \
    task.random_turn=${random_turn} \
    algo.actor.lr=0.0001 \
    algo.critic.lr=0.0001 \
    algo.train_every=64 \
    algo.initial_high_level_policy=${initial_high_level_policy} \
    first_id=${first_id} \
    run_name_suffix=${run_name_suffix} \
    solver_type=nash \
    share_population=True \
    max_iter_steps=10000 \
    mean_threshold=0.90 \
    init_by_latest_strategy=${init_by_latest_strategy}$ \
    task.drone_model=${drone_model} \
    max_population_size=${max_population_size} \
    seed=${seed} \
    SecPass_new_policy_checkpoint_path="checkpoint/checkpoint_secpass_coselfplay.pt" \
    actor_1_checkpoints_directory_path="checkpoint/high_level_old" \
    # wandb.mode=disabled # debug
    