name: psro_high_level

# ppo
train_every: 64
num_minibatches: 16
ppo_epochs: 4
clip_param: 0.1 # 0.2 可能需要搜索
entropy_coef: 0.001 # 0.01
gae_lambda: 0.95
gamma: 0.995 # 0.99
max_grad_norm: 10.0
normalize_advantages: True

share_actor: false
critic_input: obs # `obs` or `state`

initial_high_level_policy: random # 'random' or 'fixed' or 'fixed_2'

actor:
  lr: 0.0005
  lr_scheduler:
  lr_scheduler_kwargs:

  # mlp
  hidden_units: [256, 128, 128]
  layer_norm: true

  weight_decay: 0.0
  gain: 0.01

  vision_encoder: MobileNetV3Small
  attn_encoder: PartialAttentionEncoder # if applicable
  use_orthogonal: true

  create_dist_func: default
  output_dist_params: true

critic:
  num_critics: 1
  value_norm:
    class: ValueNorm1
    kwargs:
      beta: 0.995

  lr: 0.0005
  lr_scheduler:
  lr_scheduler_kwargs:

  # mlp
  hidden_units: [256, 128, 128]
  layer_norm: true

  weight_decay: 0.0
  gain: 0.01

  use_huber_loss: true
  huber_delta: 10

  vision_encoder: MobileNetV3Small
  attn_encoder: PartialAttentionEncoder # if applicable
  use_feature_normalization: true
  use_orthogonal: true
